/*
 * File: app/view/EmployeeFormPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaCrud.view.EmployeeFormPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.employeeFormPanel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    config: {
        itemId: 'employeeFormPanel',
        items: [
            {
                xtype: 'fieldset',
                itemId: 'FirstNameFieldSet',
                title: '',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'firstname',
                        label: 'First Name',
                        labelWidth: '40%'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'LastNameFieldSet',
                title: '',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'lastname',
                        label: 'Last Name',
                        labelWidth: '40%'
                    }
                ]
            }
        ]
    }

});