/*
 * File: app/controller/EmployeeController.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaCrud.controller.EmployeeController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            employeeNavigationView: {
                autoCreate: true,
                selector: 'navigationview#employeeNavigationView',
                xtype: 'employeeNavigationView'
            },
            employeeFormPanel: {
                autoCreate: true,
                selector: 'formpanel#employeeFormPanel',
                xtype: 'employeeFormPanel'
            },
            employeeList: {
                autoCreate: true,
                selector: 'list#employeeList',
                xtype: 'employeeList'
            }
        },

        control: {
            "button#employeeRefreshButton": {
                tap: 'onEmployeeRefreshButtonTap'
            },
            "button#employeeAddButton": {
                tap: 'onEmployeeAddButtonTap'
            },
            "button#employeeSaveButton": {
                tap: 'onEmployeeAddSaveButtonTap'
            },
            "list#employeeList": {
                itemtap: 'onEmployeeListItemTap'
            },
            "button#employeeDeleteButton": {
                tap: 'onEmployeeDeleteButtonTap'
            }
        }
    },

    onEmployeeRefreshButtonTap: function(button, e, eOpts) {
        var employeeJsonPStore = Ext.getStore('EmployeeJsonPStore');


        employeeJsonPStore.load();
    },

    onEmployeeAddButtonTap: function(button, e, eOpts) {
        // Get References
        var employeeNavigationView = this.getEmployeeNavigationView();
        var employeeFormPanel = this.getEmployeeFormPanel();


        // Application Logic
        var record = Ext.create('SenchaCrud.model.Employee');
        record.set('attrName','sudhir');
        employeeFormPanel.setRecord(record);

        employeeNavigationView.push(employeeFormPanel);


    },

    onEmployeeAddSaveButtonTap: function(button, e, eOpts) {
        // Get References

        var employeeNavigationView = this.getEmployeeNavigationView();
        var employeeFormPanel = this.getEmployeeFormPanel();
        var employeeList = this.getEmployeeList();
        var employeeJsonPStore = Ext.getStore('EmployeeJsonPStore');

        var employee = employeeFormPanel.getRecord();


        employeeFormPanel.updateRecord(employee);

        var operation = {};
        //operation.success = this.employeeSave;
        operation.failure = function() {
            Ext.Msg.alert(SenchaCrud.app.getGenericServerMessage(),'',Ext.emptyFn);
            return;};
        employee.set('id',0);// 0 Represents dummy id, otherwise
        //Sencha uses something like ext-* which fails on Roo server
        //side because its not integer.
        employee.save(operation);

        employeeNavigationView.pop();
    },

    onEmployeeListItemTap: function(dataview, index, target, record, e, eOpts) {
        var employeeNavigationView = this.getEmployeeNavigationView();
        var employeeFormPanel = this.getEmployeeFormPanel();

        employeeFormPanel.setRecord(record);
        employeeNavigationView.push(employeeFormPanel);

    },

    onEmployeeDeleteButtonTap: function(button, e, eOpts) {
        alert('delete');
        var employeeNavigationView = this.getEmployeeNavigationView();
        var employeeFormPanel = this.getEmployeeFormPanel();
        var employeeList = this.getEmployeeList();
        var employeeJsonPStore = Ext.getStore('EmployeeJsonPStore');

        var employee = employeeFormPanel.getRecord();


        var operation = {};

        operation.failure = function() {
            Ext.Msg.alert(SenchaCrud.app.getGenericServerMessage(),'',Ext.emptyFn);
            return;};

        employee.erase(operation);

        employeeNavigationView.pop();
    }

});